apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: test-chart
spec:
  params:
  - default: github.com
    description: where your repo is hosted exam (like "github.com" )
    name: git-url-source
    type: string
  - default: tal-hason
    description: Your GIT User name
    name: git-user
    type: string
  - default: ""
    description: Your GIT Repository name
    name: git-repo-name
    type: string
  - default: ""
    name: tag
    type: string
  - default: ""
    name: image
    type: string
  - default: ""
    name: branch
    type: string
  - default: ""
    name: git-secret-name
    type: string
  - default: ""
    name: application-name
    type: string
  - default: ""
    name: deploy-env
    type: string
  - default: ""
    name: service-name
    type: string
  - default: ""
    name: http
    type: string
  steps:
  - args:
    - -c
    - "set -ex\npwd\nmkdir workspace\ncd workspace\npwd\ngit config --global user.email
      \"tekton@pipeline.com\"\ngit config --global user.name \"$(params.git-user)\"\ngit
      clone $(params.http)://$(params.git-url-source)/$(params.git-user)/$(params.git-repo-name).git\ncd
      $(params.git-repo-name)/Application/$(params.application-name)\nls -la \necho
      \"Update image name\"\nyq -i '.image.name = \"$(params.image)\" | .image.tag
      = \"$(params.tag)\"' values-$(params.deploy-env).yaml\nyq -i '.deploy.env[0].value
      = \"$(params.image)\" | .deploy.env[1].value = \"$(params.tag)\"' values-$(params.deploy-env).yaml\ncd
      ..\nhelm install $(params.application-name) .  -f $(params.application-name)/values-$(params.deploy-env).yaml
      -n $(params.application-name)-test --set global.serviceName=test --wait\nexport
      SERVICE_HOST=`oc get route -n $(params.application-name)-test |grep -i $(params.application-name)|awk
      '{print $2}'`\ncurl https://${SERVICE_HOST}/helloworld/ -k \nhelm uninstall
      $(params.application-name) -n $(params.application-name)-test --wait \n"
    command:
    - /bin/bash
    env:
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          key: password
          name: $(params.git-secret-name)
    - name: GIT_USER
      valueFrom:
        secretKeyRef:
          key: username
          name: $(params.git-secret-name)
    image: nexus.muneerkh.local:8082/repository/my-images/tomcathelloworld:2
    name: test-chart-app-ver
    resources: {}
